import jsPDF from "jspdf";

interface AnalysisData {
  businessReality: {
    type: string;
    beginnerFriendly: string;
    biggestRisk: string;
  };
  productDecision: {
    primary: string;
    backup: string;
    reasoning: string;
  };
  sourceGuide: {
    where: string;
    costBreakdown: string;
    commonMistake: string;
  };
  deliveryPlan: {
    method: string;
    payment: string;
    riskWarning: string;
  };
  websiteDecision: {
    verdict: string;
    explanation: string;
    websiteType?: string | null;
    features?: string[] | null;
    notToBuild: string;
  };
  marketingPlan: {
    first10Customers: string[];
    whereToMarket: string;
    whatToSay: string;
    whatNotToDo: string;
  };
  actionPlan: {
    day1to3: string;
    day4to7: string;
    day8to14: string;
  };
  failureWarning: {
    whereFailOccurs: string;
    moneyLossMistake: string;
  };
}

interface FormData {
  businessIdea: string;
  businessType: string;
  budgetRange: string;
  location?: string;
}

export const generateBusinessPDF = (formData: FormData, analysis: AnalysisData): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let y = 20;

  const addText = (text: string, fontSize: number = 11, isBold: boolean = false) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, maxWidth);
    
    lines.forEach((line: string) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
        // Add watermark on each page
        addWatermark();
      }
      doc.text(line, margin, y);
      y += fontSize * 0.5;
    });
    y += 3;
  };

  const addSection = (title: string, content: string[][]) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
      addWatermark();
    }
    
    doc.setFillColor(14, 165, 133); // Teal color
    doc.rect(margin, y - 5, maxWidth, 8, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text(title, margin + 3, y);
    doc.setTextColor(0, 0, 0);
    y += 10;

    content.forEach(([label, value]) => {
      addText(`${label}: ${value}`, 10, false);
    });
    y += 5;
  };

  const addWatermark = () => {
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Nextminds AI — Powered by SA Coder", pageWidth / 2, 290, { align: "center" });
    doc.setTextColor(0, 0, 0);
  };

  // Header
  doc.setFillColor(14, 165, 133);
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("Nextminds AI", pageWidth / 2, 18, { align: "center" });
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Business Execution Plan", pageWidth / 2, 28, { align: "center" });
  doc.setFontSize(8);
  doc.text("Powered by SA Coder", pageWidth / 2, 36, { align: "center" });
  doc.setTextColor(0, 0, 0);
  y = 50;

  // Business Info
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Business Idea:", margin, y);
  doc.setFont("helvetica", "normal");
  y += 5;
  const ideaLines = doc.splitTextToSize(formData.businessIdea, maxWidth);
  ideaLines.slice(0, 3).forEach((line: string) => {
    doc.text(line, margin, y);
    y += 5;
  });
  y += 5;

  doc.text(`Type: ${formData.businessType} | Budget: ${formData.budgetRange}${formData.location ? ` | Location: ${formData.location}` : ""}`, margin, y);
  y += 15;

  // Add watermark
  addWatermark();

  // Sections
  addSection("1. Business Reality Check", [
    ["Business Type", analysis.businessReality.type],
    ["Beginner Friendly", analysis.businessReality.beginnerFriendly],
    ["Biggest Risk", analysis.businessReality.biggestRisk]
  ]);

  addSection("2. Product / Service Decision", [
    ["Primary Recommendation", analysis.productDecision.primary],
    ["Backup Option", analysis.productDecision.backup],
    ["Reasoning", analysis.productDecision.reasoning]
  ]);

  addSection("3. Product Source Guide", [
    ["Where to Source", analysis.sourceGuide.where],
    ["Cost Breakdown", analysis.sourceGuide.costBreakdown],
    ["Common Mistake", analysis.sourceGuide.commonMistake]
  ]);

  addSection("4. Delivery & Fulfillment", [
    ["Method", analysis.deliveryPlan.method],
    ["Payment", analysis.deliveryPlan.payment],
    ["Risk Warning", analysis.deliveryPlan.riskWarning]
  ]);

  addSection("5. Website Decision", [
    ["Verdict", analysis.websiteDecision.verdict],
    ["Explanation", analysis.websiteDecision.explanation],
    ...(analysis.websiteDecision.websiteType ? [["Website Type", analysis.websiteDecision.websiteType]] : []),
    ...(analysis.websiteDecision.features ? [["Features", analysis.websiteDecision.features.join(", ")]] : []),
    ["Not To Build", analysis.websiteDecision.notToBuild]
  ]);

  addSection("6. Marketing Plan", [
    ["First 10 Customers", analysis.marketingPlan.first10Customers.join(" | ")],
    ["Where to Market", analysis.marketingPlan.whereToMarket],
    ["What to Say", analysis.marketingPlan.whatToSay],
    ["What NOT to Do", analysis.marketingPlan.whatNotToDo]
  ]);

  addSection("7. 14-Day Action Plan", [
    ["Day 1-3", analysis.actionPlan.day1to3],
    ["Day 4-7", analysis.actionPlan.day4to7],
    ["Day 8-14", analysis.actionPlan.day8to14]
  ]);

  addSection("8. Failure Warning", [
    ["Where Most Fail", analysis.failureWarning.whereFailOccurs],
    ["Money Loss Mistake", analysis.failureWarning.moneyLossMistake]
  ]);

  // Final footer
  doc.addPage();
  addWatermark();
  y = 100;
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("Thank You for Using Nextminds AI!", pageWidth / 2, y, { align: "center" });
  y += 15;
  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Powered by SA Coder", pageWidth / 2, y, { align: "center" });

  // Save
  const filename = `Nextminds-AI-Plan-${new Date().toISOString().split("T")[0]}.pdf`;
  doc.save(filename);
};
